name: dorm_list
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_size_text_field: ^2.2.3
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.10+1
  google_fonts: 6.2.1
  provider: ^6.0.0
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/dorms/
    - assets/images/
    - assets/svgs/
    - assets/images/gf_minji.png

fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf