name: dorm_list
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.3
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  get: ^4.6.6
  google_fonts: 6.2.1
  image_picker: ^1.1.1
  provider: ^6.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.10+1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/dorms/
    - assets/images/
    - assets/svgs/
    - assets/images/gf_minji.png

fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf
